apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notebook-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: notebook-pv
  storageClassName: ""
