apiVersion: v1
kind: Service
metadata:
  name: tvm-cuda-jupyter-service
spec:
  selector:
    app: tvm-cuda-jupyter
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
