apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: mlflow-server
        image: tairayuzuki52431679/depplearning:mlflow-latest
        ports:
        - containerPort: 5000
      volumes:
      - name: mlflow-storage
        persistentVolumeClaim:
          claimName: mlflow-pvc
