# GPUを使用する想定。CUDAのバージョンに合わせたNVIDIAのCUDAイメージを使用
# リポジトリ https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/supported-tags.md
FROM nvidia/cuda:12.3.1-devel-ubuntu22.04

# 必要なパッケージをインストール
RUN apt-get update && apt-get install -y \
    python3-pip

# 作業ディレクトリを設定
WORKDIR /app

# 必要なPythonパッケージをインストール
COPY requirements.txt /app/requirements.txt
RUN pip3 install -r requirements.txt


# 必要なスクリプトをコピー
COPY /scripts/get_qiita.py /app/get_qiita.py